const products = [
    {
        category: "smartphones",
        subcategory: "Apple",
        name: "Смартфон Apple iPhone 14 128 ГБ",
        price: "84 999",
        oldPrice: "87 999",
        availability: "Нет в наличии",
        image: "/src/Pictures/iphone 14-128.png",
        discount: "- 4 %",
        memory: "128 ГБ",
        ram: "6 ГБ",
        display: "Super Retina XDR, 2796x1290",
        main_cam: "48+12+12 Мп",
        brand: "apple",
    },
    {
        category: "smartphones",
        subcategory: "apple",
        name: "Смартфон Apple iPhone 11 64 ГБ",
        price: "42 999",
        oldPrice: "47 456",
        availability: "В наличии",
        image: "/src/Pictures/Apple Iphone 12 64.png",
        discount: "- 10 %",
        memory: "64 ГБ",
        display: "Liquid Retina HD, 1792x828",
        main_cam: "12+12 Мп",
        ram: "4 ГБ",
        brand: "apple"
    },
    {
        category: "smartphones",
        subcategory: "huawei",
        name: "Смартфон HUAWEI nova Y61 128ГБ",
        price: "11 990",
        oldPrice: "14 117",
        availability: "В наличии",
        image: "/src/Pictures/Huawei.png",
        discount: "- 15 %",
        memory: "128  ГБ",
        display: "IPS, 1600x720",
        main_cam: "50+2+2 Мп",
        ram: "4 ГБ",
        brand: "huawei"
    },
    {
        category: "smartphones",
        subcategory: "xiaomi",
        name: "Смартфон Xiaomi Redmi  128 ГБ",
        price: "17 665",
        oldPrice: "17 999 ",
        availability: "В наличии",
        image: "/src/Pictures/Redmi.png",
        discount: "- 4 %",
        display: "IPS, 1600x720",
        memory: "128GB",
        main_cam: "50+2+0.08 Мп",
        ram: "4 ГБ",
        brand: "xiaomi"
    },
    {
        category: "smartphones",
        subcategory: "apple",
        name: "Смартфон Apple iPhone 13 128 ГБ",
        price: "75 999",
        oldPrice: "77 999",
        availability: "В наличии",
        image: "/src/Pictures/Iphone 12.png",
        discount: "- 5 %",
        memory: "128GB",
        display: "Super Retina XDR, 2532x1170",
        ram: "4 ГБ",
        main_cam: "12+12 Мп",
        brand: "apple"
    },
    {
        category: "smartspeakers",
        subcategory: "google",
        name: "Google Nest",
        price: "75 999",
        oldPrice: "77 999",
        availability: "В наличии",
        image: "/src/Pictures/Google_Nest.png",
        //discount: "- 5 %"
    }
];

export default products;